SELECT BK.BOOK_ID, AU.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK BK
LEFT JOIN AUTHOR AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY BK.PUBLISHED_DATE;